### PR TITLE
Disable bitcode.

### PR DESCRIPTION
**Pull request by e2l3n**
<b>Description</b>: 
Disable `bitcode` compilation of the main target of a `Cordova` application. 
Currently the hardcoded values reside at the `xcconfig` file generated by this [script](https://github.com/Icenium/BpcTooling/blob/master/BuildScripts/node_build/modules/cordova/ios/build-utilities.js#L113) and this causes problems when building for `watchOS 2.0` apps which nowadays require `bitcode` compilation.

<b>Details:</b> See the following PRs which are also part of the changes that add support for `watchOS 2.0` https://github.com/Icenium/BpcTooling/pull/395, https://github.com/Telerik-Verified-Plugins/AppleWatch/pull/19.

### CODE REVIEW

**Comment by e2l3n** [comment]
ping @galexandrov @zahhak @Mitko-Kerezov

**Comment by galexandrov** [comment]
:+1:

**Comment by mbektchiev** [comment]
:+1: You can replace the spaces with tabs in newly added lines. It's not a merge-stopper.

**Comment by mbektchiev** [comment]
You should make this change in `build-4.0.0` and `build-5.0.0` branches and update the respective submodules in BpcTooling.

**Comment by galexandrov** [comment]
We can use variable for the Bitcode in pbx project
But for now we can have it hard coded :+1:

**Comment by e2l3n** [comment]
Setting `ENABLE_BITCODE = NO` affects the watch target as well which somehow inherits the setting from the main target settings.

**Pull request closed without merging**
